/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pengmin_encryption_YHJniUtils */

#ifndef _Included_com_pengmin_encryption_YHJniUtils
#define _Included_com_pengmin_encryption_YHJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pengmin_encryption_YHJniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pengmin_encryption_YHJniUtils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
